Implement method addToWishListFromCart
brayan9304/spartacus-training pull request #48
Opened 2022-05-04 16:31 UTC by JsonVM

2022-05-04 16:42 UTC, Carlangasv approved these changes

2022-05-04 16:48 UTC, fer9972 requested changes

2022-05-04 16:48 UTC, fer9972 commented on core-customize/tccommercewebservices/web/src/com/taloscommerce/webservices/v2/controller/SelectiveCartController.java
> +    private DefaultUserService defaultUserService;
this dependency injection is not used.

2022-05-05 13:23 UTC, JsonVM commented on core-customize/tccommercewebservices/web/src/com/taloscommerce/webservices/v2/controller/SelectiveCartController.java
> +    private DefaultUserService defaultUserService;
fixed

2022-05-05 13:25 UTC, fer9972 approved these changes

2022-05-05 13:27 UTC, merged