Added Event and EventListener of SendOldProductInWishList and the bea…
brayan9304/spartacus-training pull request #56
Opened 2022-05-10 22:21 UTC by BryanTorresCalle

Added files Event, EventListener of SendOldProductInWishList and implemented.
Added bean of the event listener

2022-05-10 23:52 UTC, JsonVM requested changes

2022-05-10 23:52 UTC, JsonVM commented on core-customize/tccore/resources/tccore-spring.xml
> +        <property name="modelService" ref="modelService"/>
I recommend use constructor arg instead property

2022-05-11 13:44 UTC, fer9972 requested changes

2022-05-11 13:44 UTC, fer9972 commented on core-customize/tccore/src/com/taloscommerce/core/event/SendOldProductInWishListEventListener.java
> +        final List<ProductModel> products = sendOldProductInWishListEvent.getProducts();
I recommend that the product variable be called oldProducts just to have a better reference of what we are saving there

2022-05-11 13:44 UTC, fer9972 commented on core-customize/tccore/src/com/taloscommerce/core/event/SendOldProductInWishListEvent.java
> +    private List<ProductModel> products;
I recommend that the product variable be called oldProducts just to have a better reference of what we are saving there

2022-05-11 13:57 UTC, Carlangasv approved these changes

2022-05-11 14:02 UTC, fer9972 approved these changes

2022-05-11 14:09 UTC, JsonVM approved these changes

2022-05-11 14:09 UTC, merged